WIP: Experimental kube-gen support"
kube-node/nodeset pull request #6
Opened 2017-08-14 08:11 UTC by sttts

2017-08-18 09:15 UTC, mrIncompetent requested changes

2017-08-18 09:15 UTC, mrIncompetent commented on glide.yaml
> +#  version: a9bfd91dd998b4ab203bc0bb011d4b5ac15dbaab # that's 1.7, branch is missing
I'm not a big fan of commented out code. Can we remove this?

2017-08-18 09:17 UTC, sttts commented on glide.yaml
> +#  version: a9bfd91dd998b4ab203bc0bb011d4b5ac15dbaab # that's 1.7, branch is missing
Waiting for Godo^Whttps://github.com/kubernetes/test-infra/pull/3559

2017-08-20 15:17 UTC, ledzep2 commented on hack/update-codegen.sh
> +CLIENT_NAME=clientset
Are we going for an unversioned client? The types are still versioned.

2017-08-20 15:25 UTC, ledzep2 commented on pkg/client/clientset/typed/nodeset/v1alpha1/nodeclass.go
> -		Namespace(v1alpha1.TPRNamespace).
Are we moving to CRD only?

2017-08-20 15:32 UTC, sttts commented on hack/update-codegen.sh
> +CLIENT_NAME=clientset
No, still versioned. But if we get other versions as well, they will be part of the same clientset. At least that was the plan.

2017-08-20 15:32 UTC, sttts commented on pkg/client/clientset/typed/nodeset/v1alpha1/nodeclass.go
> -		Namespace(v1alpha1.TPRNamespace).
TPRs will not exist anymore in 1.8, and are already deprecated in 1.7. We have to.

2017-10-06 12:36 UTC, mrIncompetent approved these changes

2017-10-27 15:18 UTC, mrIncompetent commented
@ledzep2 @adieu PTAL

2017-11-02 13:12 UTC, mrIncompetent approved these changes

2017-11-02 13:18 UTC, mrIncompetent commented
/lgtm

2017-11-02 13:25 UTC, sttts commented
Merging.

2017-11-02 13:25 UTC, merged